### ISSUE TITLE
Add Validations

### ISSUE THREAD

**Issue by SuyashRajput** [Open-Source-Chandigarh/Expense-Tracker#13]
Here a simple and good first issue for new Open Source Contributors
![image](https://github.com/Open-Source-Chandigarh/Expense-Tracker/assets/110171204/2eb507ce-8f42-4836-ab9d-ae94517ffe62)
Add validations to the landing page form and the budget alert.

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @SuyashRajput , @BamaCharanChhandogi 

I would like to fix this, actually, I found it why it is happening, where the user enters an empty budget. I fixed it and instead of NaN, it will set the value to 0.  

I think it is good to prompt the alert message again when the user didn't enter the value. Even if the user enters a string value I mean name or anything that is not a number. It will check for it.

**Comment by BamaCharanChhandogi** [comment]
Free fill to raise PR. I will check

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @BamaCharanChhandogi 

please assign me this issue, I fixed this issue already and also add the Hacktober tag too. 😊

When user enters

negative
text
empty input value. 

Then it will again ask the user to enter the budget.
